### ISSUE TITLE
dockerize this repo in an image with all dependencies needed to run the benchmarks.

### ISSUE THREAD

**Issue by thegreyfellow** [clux/magic-forest#13]
Hi, love it! I like the idea and love how this shows the performance gaps between languages without any optimization.

I would love to run the benchmarks but I don't want to install all these languages in my personal machine, a suggestion is to make a docker image with all dependencies needed where we can just run the container and then start the benchmarks.

Thank you for this 😸

**Comment by clux** [comment]
Hey, thanks lot. Glad you found it interesting.

There is a `Dockerfile` in the repo that should work, at least it did a while ago. But you'll have to build it yourself as it's based on Arch and ended up too large and annoying to push. See the [3 lines from travis.yml](https://github.com/clux/magic-forest/blob/2374c02f9e7a0b1c843e3a99df582b7d672bd5d4/.travis.yml#L4-L8) and you should be able to run the tests in docker :-)

**Comment by clux** [comment]
`docker build -t clux/magic-forest .` in this repo still works [from travis](https://travis-ci.org/clux/magic-forest/builds/331259558). 6 minute docker build. Closing :-)
